### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by ghost** [bobb-Rob/portfolio-project-1#5]
Ali:
Please add your partners as authors in the README file.

Chahine:
The requirements of the project are well implemented.
I suggest using fewer id selectors and using classes instead.
Commits should be verbs in the present tense describing the changes.

Tahseen:
See line 73 of index.html file: better to select the li with ".tags > li {}"
On line 51 the image name and "alt" attribute are not descriptive.

**Comment by bobb-Rob** [comment]
@chahine-mahdhi Thank you so much for this. This is very well noted.
